apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: 10024-23-7-1001
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 60